# Cross compiling from linux using mingw32 tools
# On ubuntu, you'll need to install the packages: mingw32, mingw32-binutils, mingw32-runtime
#
# Use of this file:
# cmake -DCMAKE_TOOLCHAIN_FILE=../cmake/Toolchain-mingw32.cmake ..

INCLUDE(/opt/mxe/usr/x86_64-w64-mingw32.shared/share/cmake/mxe-conf.cmake)

SET(_CL_HAVE_GCC_ATOMIC_FUNCTIONS_EXITCODE 0)

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)

SET(_CL_HAVE_GCCVISIBILITYPATCH 0)
SET(_CL_HAVE_NAMESPACES_EXITCODE 0)
SET(_CL_HAVE_NO_SNPRINTF_BUG_EXITCODE 0)
SET(_CL_HAVE_NO_SNWPRINTF_BUG_EXITCODE 0)
SET(LUCENE_STATIC_CONSTANT_SYNTAX_EXITCODE 1)
SET(_CL_HAVE_TRY_BLOCKS_EXITCODE 0)
SET(_CL_HAVE_WIN32_THREADS 0)

SET(CMAKE_FIND_ROOT_PATH "/opt/mxe/usr/x86_64-w64-mingw32.shared")
